"""Accent fallback character mapping for Unicode to ASCII conversion.

This module provides the ACCENT_FALLBACK_MAP dictionary for accented characters
and symbols. Used when the target codepage doesn't support the character directly.
The transcoding logic checks direct encoding first, so characters that exist
in the target codepage (e.g., +/- in CP437) will be preserved, not replaced.
"""

from __future__ import annotations

# Extended mapping for accented characters and symbols to fallback representations
# Used when the target codepage doesn't support the character directly.
# Note: The transcoding logic checks direct encoding first, so characters that exist
# in the target codepage (e.g., +/- in CP437) will be preserved, not replaced.
ACCENT_FALLBACK_MAP: dict[str, str] = {
    # Symbols that exist in some codepages (e.g., CP437) but not others
    # These are only used as fallbacks when direct encoding fails
    "\u00b1": "+/-",  # PLUS-MINUS SIGN (in CP437, fallback for others)
    "\u00f7": "/",  # DIVISION SIGN (in CP437, fallback for others)
    "\u00bc": "1/4",  # VULGAR FRACTION ONE QUARTER (in CP437, fallback for others)
    "\u00bd": "1/2",  # VULGAR FRACTION ONE HALF (in CP437, fallback for others)
    "\u00a3": "GBP",  # POUND SIGN (in CP437, fallback for others)
    "\u00a5": "JPY",  # YEN SIGN (in CP437, fallback for others)
    # Latin Extended-A and Extended-B characters
    "\u0100": "A",  # LATIN CAPITAL LETTER A WITH MACRON
    "\u0101": "a",  # LATIN SMALL LETTER A WITH MACRON
    "\u0102": "A",  # LATIN CAPITAL LETTER A WITH BREVE
    "\u0103": "a",  # LATIN SMALL LETTER A WITH BREVE
    "\u0104": "A",  # LATIN CAPITAL LETTER A WITH OGONEK
    "\u0105": "a",  # LATIN SMALL LETTER A WITH OGONEK
    "\u0106": "C",  # LATIN CAPITAL LETTER C WITH ACUTE
    "\u0107": "c",  # LATIN SMALL LETTER C WITH ACUTE
    "\u0108": "C",  # LATIN CAPITAL LETTER C WITH CIRCUMFLEX
    "\u0109": "c",  # LATIN SMALL LETTER C WITH CIRCUMFLEX
    "\u010a": "C",  # LATIN CAPITAL LETTER C WITH DOT ABOVE
    "\u010b": "c",  # LATIN SMALL LETTER C WITH DOT ABOVE
    "\u010c": "C",  # LATIN CAPITAL LETTER C WITH CARON
    "\u010d": "c",  # LATIN SMALL LETTER C WITH CARON
    "\u010e": "D",  # LATIN CAPITAL LETTER D WITH CARON
    "\u010f": "d",  # LATIN SMALL LETTER D WITH CARON
    "\u0110": "D",  # LATIN CAPITAL LETTER D WITH STROKE
    "\u0111": "d",  # LATIN SMALL LETTER D WITH STROKE
    "\u0112": "E",  # LATIN CAPITAL LETTER E WITH MACRON
    "\u0113": "e",  # LATIN SMALL LETTER E WITH MACRON
    "\u0114": "E",  # LATIN CAPITAL LETTER E WITH BREVE
    "\u0115": "e",  # LATIN SMALL LETTER E WITH BREVE
    "\u0116": "E",  # LATIN CAPITAL LETTER E WITH DOT ABOVE
    "\u0117": "e",  # LATIN SMALL LETTER E WITH DOT ABOVE
    "\u0118": "E",  # LATIN CAPITAL LETTER E WITH OGONEK
    "\u0119": "e",  # LATIN SMALL LETTER E WITH OGONEK
    "\u011a": "E",  # LATIN CAPITAL LETTER E WITH CARON
    "\u011b": "e",  # LATIN SMALL LETTER E WITH CARON
    "\u011c": "G",  # LATIN CAPITAL LETTER G WITH CIRCUMFLEX
    "\u011d": "g",  # LATIN SMALL LETTER G WITH CIRCUMFLEX
    "\u011e": "G",  # LATIN CAPITAL LETTER G WITH BREVE
    "\u011f": "g",  # LATIN SMALL LETTER G WITH BREVE
    "\u0120": "G",  # LATIN CAPITAL LETTER G WITH DOT ABOVE
    "\u0121": "g",  # LATIN SMALL LETTER G WITH DOT ABOVE
    "\u0122": "G",  # LATIN CAPITAL LETTER G WITH CEDILLA
    "\u0123": "g",  # LATIN SMALL LETTER G WITH CEDILLA
    "\u0124": "H",  # LATIN CAPITAL LETTER H WITH CIRCUMFLEX
    "\u0125": "h",  # LATIN SMALL LETTER H WITH CIRCUMFLEX
    "\u0126": "H",  # LATIN CAPITAL LETTER H WITH STROKE
    "\u0127": "h",  # LATIN SMALL LETTER H WITH STROKE
    "\u0128": "I",  # LATIN CAPITAL LETTER I WITH TILDE
    "\u0129": "i",  # LATIN SMALL LETTER I WITH TILDE
    "\u012a": "I",  # LATIN CAPITAL LETTER I WITH MACRON
    "\u012b": "i",  # LATIN SMALL LETTER I WITH MACRON
    "\u012c": "I",  # LATIN CAPITAL LETTER I WITH BREVE
    "\u012d": "i",  # LATIN SMALL LETTER I WITH BREVE
    "\u012e": "I",  # LATIN CAPITAL LETTER I WITH OGONEK
    "\u012f": "i",  # LATIN SMALL LETTER I WITH OGONEK
    "\u0130": "I",  # LATIN CAPITAL LETTER I WITH DOT ABOVE
    "\u0131": "i",  # LATIN SMALL LETTER DOTLESS I
    "\u0134": "J",  # LATIN CAPITAL LETTER J WITH CIRCUMFLEX
    "\u0135": "j",  # LATIN SMALL LETTER J WITH CIRCUMFLEX
    "\u0136": "K",  # LATIN CAPITAL LETTER K WITH CEDILLA
    "\u0137": "k",  # LATIN SMALL LETTER K WITH CEDILLA
    "\u0139": "L",  # LATIN CAPITAL LETTER L WITH ACUTE
    "\u013a": "l",  # LATIN SMALL LETTER L WITH ACUTE
    "\u013b": "L",  # LATIN CAPITAL LETTER L WITH CEDILLA
    "\u013c": "l",  # LATIN SMALL LETTER L WITH CEDILLA
    "\u013d": "L",  # LATIN CAPITAL LETTER L WITH CARON
    "\u013e": "l",  # LATIN SMALL LETTER L WITH CARON
    "\u0141": "L",  # LATIN CAPITAL LETTER L WITH STROKE
    "\u0142": "l",  # LATIN SMALL LETTER L WITH STROKE
    "\u0143": "N",  # LATIN CAPITAL LETTER N WITH ACUTE
    "\u0144": "n",  # LATIN SMALL LETTER N WITH ACUTE
    "\u0145": "N",  # LATIN CAPITAL LETTER N WITH CEDILLA
    "\u0146": "n",  # LATIN SMALL LETTER N WITH CEDILLA
    "\u0147": "N",  # LATIN CAPITAL LETTER N WITH CARON
    "\u0148": "n",  # LATIN SMALL LETTER N WITH CARON
    "\u014c": "O",  # LATIN CAPITAL LETTER O WITH MACRON
    "\u014d": "o",  # LATIN SMALL LETTER O WITH MACRON
    "\u014e": "O",  # LATIN CAPITAL LETTER O WITH BREVE
    "\u014f": "o",  # LATIN SMALL LETTER O WITH BREVE
    "\u0150": "O",  # LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
    "\u0151": "o",  # LATIN SMALL LETTER O WITH DOUBLE ACUTE
    "\u0152": "OE",  # LATIN CAPITAL LIGATURE OE
    "\u0153": "oe",  # LATIN SMALL LIGATURE OE
    "\u0154": "R",  # LATIN CAPITAL LETTER R WITH ACUTE
    "\u0155": "r",  # LATIN SMALL LETTER R WITH ACUTE
    "\u0156": "R",  # LATIN CAPITAL LETTER R WITH CEDILLA
    "\u0157": "r",  # LATIN SMALL LETTER R WITH CEDILLA
    "\u0158": "R",  # LATIN CAPITAL LETTER R WITH CARON
    "\u0159": "r",  # LATIN SMALL LETTER R WITH CARON
    "\u015a": "S",  # LATIN CAPITAL LETTER S WITH ACUTE
    "\u015b": "s",  # LATIN SMALL LETTER S WITH ACUTE
    "\u015c": "S",  # LATIN CAPITAL LETTER S WITH CIRCUMFLEX
    "\u015d": "s",  # LATIN SMALL LETTER S WITH CIRCUMFLEX
    "\u015e": "S",  # LATIN CAPITAL LETTER S WITH CEDILLA
    "\u015f": "s",  # LATIN SMALL LETTER S WITH CEDILLA
    "\u0160": "S",  # LATIN CAPITAL LETTER S WITH CARON
    "\u0161": "s",  # LATIN SMALL LETTER S WITH CARON
    "\u0162": "T",  # LATIN CAPITAL LETTER T WITH CEDILLA
    "\u0163": "t",  # LATIN SMALL LETTER T WITH CEDILLA
    "\u0164": "T",  # LATIN CAPITAL LETTER T WITH CARON
    "\u0165": "t",  # LATIN SMALL LETTER T WITH CARON
    "\u0166": "T",  # LATIN CAPITAL LETTER T WITH STROKE
    "\u0167": "t",  # LATIN SMALL LETTER T WITH STROKE
    "\u0168": "U",  # LATIN CAPITAL LETTER U WITH TILDE
    "\u0169": "u",  # LATIN SMALL LETTER U WITH TILDE
    "\u016a": "U",  # LATIN CAPITAL LETTER U WITH MACRON
    "\u016b": "u",  # LATIN SMALL LETTER U WITH MACRON
    "\u016c": "U",  # LATIN CAPITAL LETTER U WITH BREVE
    "\u016d": "u",  # LATIN SMALL LETTER U WITH BREVE
    "\u016e": "U",  # LATIN CAPITAL LETTER U WITH RING ABOVE
    "\u016f": "u",  # LATIN SMALL LETTER U WITH RING ABOVE
    "\u0170": "U",  # LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
    "\u0171": "u",  # LATIN SMALL LETTER U WITH DOUBLE ACUTE
    "\u0172": "U",  # LATIN CAPITAL LETTER U WITH OGONEK
    "\u0173": "u",  # LATIN SMALL LETTER U WITH OGONEK
    "\u0174": "W",  # LATIN CAPITAL LETTER W WITH CIRCUMFLEX
    "\u0175": "w",  # LATIN SMALL LETTER W WITH CIRCUMFLEX
    "\u0176": "Y",  # LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
    "\u0177": "y",  # LATIN SMALL LETTER Y WITH CIRCUMFLEX
    "\u0178": "Y",  # LATIN CAPITAL LETTER Y WITH DIAERESIS
    "\u0179": "Z",  # LATIN CAPITAL LETTER Z WITH ACUTE
    "\u017a": "z",  # LATIN SMALL LETTER Z WITH ACUTE
    "\u017b": "Z",  # LATIN CAPITAL LETTER Z WITH DOT ABOVE
    "\u017c": "z",  # LATIN SMALL LETTER Z WITH DOT ABOVE
    "\u017d": "Z",  # LATIN CAPITAL LETTER Z WITH CARON
    "\u017e": "z",  # LATIN SMALL LETTER Z WITH CARON
    # Greek letters (common in technical contexts)
    "\u0391": "A",  # GREEK CAPITAL LETTER ALPHA
    "\u0392": "B",  # GREEK CAPITAL LETTER BETA
    "\u0393": "G",  # GREEK CAPITAL LETTER GAMMA
    "\u0394": "D",  # GREEK CAPITAL LETTER DELTA
    "\u0395": "E",  # GREEK CAPITAL LETTER EPSILON
    "\u0396": "Z",  # GREEK CAPITAL LETTER ZETA
    "\u0397": "H",  # GREEK CAPITAL LETTER ETA
    "\u0398": "TH",  # GREEK CAPITAL LETTER THETA
    "\u0399": "I",  # GREEK CAPITAL LETTER IOTA
    "\u039a": "K",  # GREEK CAPITAL LETTER KAPPA
    "\u039b": "L",  # GREEK CAPITAL LETTER LAMDA
    "\u039c": "M",  # GREEK CAPITAL LETTER MU
    "\u039d": "N",  # GREEK CAPITAL LETTER NU
    "\u039e": "X",  # GREEK CAPITAL LETTER XI
    "\u039f": "O",  # GREEK CAPITAL LETTER OMICRON
    "\u03a0": "P",  # GREEK CAPITAL LETTER PI
    "\u03a1": "R",  # GREEK CAPITAL LETTER RHO
    "\u03a3": "S",  # GREEK CAPITAL LETTER SIGMA
    "\u03a4": "T",  # GREEK CAPITAL LETTER TAU
    "\u03a5": "Y",  # GREEK CAPITAL LETTER UPSILON
    "\u03a6": "PH",  # GREEK CAPITAL LETTER PHI
    "\u03a7": "CH",  # GREEK CAPITAL LETTER CHI
    "\u03a8": "PS",  # GREEK CAPITAL LETTER PSI
    "\u03a9": "O",  # GREEK CAPITAL LETTER OMEGA
    "\u03b1": "a",  # GREEK SMALL LETTER ALPHA
    "\u03b2": "b",  # GREEK SMALL LETTER BETA
    "\u03b3": "g",  # GREEK SMALL LETTER GAMMA
    "\u03b4": "d",  # GREEK SMALL LETTER DELTA
    "\u03b5": "e",  # GREEK SMALL LETTER EPSILON
    "\u03b6": "z",  # GREEK SMALL LETTER ZETA
    "\u03b7": "h",  # GREEK SMALL LETTER ETA
    "\u03b8": "th",  # GREEK SMALL LETTER THETA
    "\u03b9": "i",  # GREEK SMALL LETTER IOTA
    "\u03ba": "k",  # GREEK SMALL LETTER KAPPA
    "\u03bb": "l",  # GREEK SMALL LETTER LAMDA
    "\u03bc": "u",  # GREEK SMALL LETTER MU
    "\u03bd": "v",  # GREEK SMALL LETTER NU
    "\u03be": "x",  # GREEK SMALL LETTER XI
    "\u03bf": "o",  # GREEK SMALL LETTER OMICRON
    "\u03c0": "pi",  # GREEK SMALL LETTER PI
    "\u03c1": "r",  # GREEK SMALL LETTER RHO
    "\u03c2": "s",  # GREEK SMALL LETTER FINAL SIGMA
    "\u03c3": "s",  # GREEK SMALL LETTER SIGMA
    "\u03c4": "t",  # GREEK SMALL LETTER TAU
    "\u03c5": "y",  # GREEK SMALL LETTER UPSILON
    "\u03c6": "ph",  # GREEK SMALL LETTER PHI
    "\u03c7": "ch",  # GREEK SMALL LETTER CHI
    "\u03c8": "ps",  # GREEK SMALL LETTER PSI
    "\u03c9": "o",  # GREEK SMALL LETTER OMEGA
    # Cyrillic (basic transliteration)
    "\u0410": "A",  # CYRILLIC CAPITAL LETTER A
    "\u0411": "B",  # CYRILLIC CAPITAL LETTER BE
    "\u0412": "V",  # CYRILLIC CAPITAL LETTER VE
    "\u0413": "G",  # CYRILLIC CAPITAL LETTER GHE
    "\u0414": "D",  # CYRILLIC CAPITAL LETTER DE
    "\u0415": "E",  # CYRILLIC CAPITAL LETTER IE
    "\u0416": "ZH",  # CYRILLIC CAPITAL LETTER ZHE
    "\u0417": "Z",  # CYRILLIC CAPITAL LETTER ZE
    "\u0418": "I",  # CYRILLIC CAPITAL LETTER I
    "\u0419": "Y",  # CYRILLIC CAPITAL LETTER SHORT I
    "\u041a": "K",  # CYRILLIC CAPITAL LETTER KA
    "\u041b": "L",  # CYRILLIC CAPITAL LETTER EL
    "\u041c": "M",  # CYRILLIC CAPITAL LETTER EM
    "\u041d": "N",  # CYRILLIC CAPITAL LETTER EN
    "\u041e": "O",  # CYRILLIC CAPITAL LETTER O
    "\u041f": "P",  # CYRILLIC CAPITAL LETTER PE
    "\u0420": "R",  # CYRILLIC CAPITAL LETTER ER
    "\u0421": "S",  # CYRILLIC CAPITAL LETTER ES
    "\u0422": "T",  # CYRILLIC CAPITAL LETTER TE
    "\u0423": "U",  # CYRILLIC CAPITAL LETTER U
    "\u0424": "F",  # CYRILLIC CAPITAL LETTER EF
    "\u0425": "KH",  # CYRILLIC CAPITAL LETTER HA
    "\u0426": "TS",  # CYRILLIC CAPITAL LETTER TSE
    "\u0427": "CH",  # CYRILLIC CAPITAL LETTER CHE
    "\u0428": "SH",  # CYRILLIC CAPITAL LETTER SHA
    "\u0429": "SHCH",  # CYRILLIC CAPITAL LETTER SHCHA
    "\u042a": "",  # CYRILLIC CAPITAL LETTER HARD SIGN
    "\u042b": "Y",  # CYRILLIC CAPITAL LETTER YERU
    "\u042c": "",  # CYRILLIC CAPITAL LETTER SOFT SIGN
    "\u042d": "E",  # CYRILLIC CAPITAL LETTER E
    "\u042e": "YU",  # CYRILLIC CAPITAL LETTER YU
    "\u042f": "YA",  # CYRILLIC CAPITAL LETTER YA
    "\u0430": "a",  # CYRILLIC SMALL LETTER A
    "\u0431": "b",  # CYRILLIC SMALL LETTER BE
    "\u0432": "v",  # CYRILLIC SMALL LETTER VE
    "\u0433": "g",  # CYRILLIC SMALL LETTER GHE
    "\u0434": "d",  # CYRILLIC SMALL LETTER DE
    "\u0435": "e",  # CYRILLIC SMALL LETTER IE
    "\u0436": "zh",  # CYRILLIC SMALL LETTER ZHE
    "\u0437": "z",  # CYRILLIC SMALL LETTER ZE
    "\u0438": "i",  # CYRILLIC SMALL LETTER I
    "\u0439": "y",  # CYRILLIC SMALL LETTER SHORT I
    "\u043a": "k",  # CYRILLIC SMALL LETTER KA
    "\u043b": "l",  # CYRILLIC SMALL LETTER EL
    "\u043c": "m",  # CYRILLIC SMALL LETTER EM
    "\u043d": "n",  # CYRILLIC SMALL LETTER EN
    "\u043e": "o",  # CYRILLIC SMALL LETTER O
    "\u043f": "p",  # CYRILLIC SMALL LETTER PE
    "\u0440": "r",  # CYRILLIC SMALL LETTER ER
    "\u0441": "s",  # CYRILLIC SMALL LETTER ES
    "\u0442": "t",  # CYRILLIC SMALL LETTER TE
    "\u0443": "u",  # CYRILLIC SMALL LETTER U
    "\u0444": "f",  # CYRILLIC SMALL LETTER EF
    "\u0445": "kh",  # CYRILLIC SMALL LETTER HA
    "\u0446": "ts",  # CYRILLIC SMALL LETTER TSE
    "\u0447": "ch",  # CYRILLIC SMALL LETTER CHE
    "\u0448": "sh",  # CYRILLIC SMALL LETTER SHA
    "\u0449": "shch",  # CYRILLIC SMALL LETTER SHCHA
    "\u044a": "",  # CYRILLIC SMALL LETTER HARD SIGN
    "\u044b": "y",  # CYRILLIC SMALL LETTER YERU
    "\u044c": "",  # CYRILLIC SMALL LETTER SOFT SIGN
    "\u044d": "e",  # CYRILLIC SMALL LETTER E
    "\u044e": "yu",  # CYRILLIC SMALL LETTER YU
    "\u044f": "ya",  # CYRILLIC SMALL LETTER YA
    # Common Latin-1 Supplement (fallbacks when not in codepage)
    "\u00c0": "A",  # LATIN CAPITAL LETTER A WITH GRAVE
    "\u00c1": "A",  # LATIN CAPITAL LETTER A WITH ACUTE
    "\u00c2": "A",  # LATIN CAPITAL LETTER A WITH CIRCUMFLEX
    "\u00c3": "A",  # LATIN CAPITAL LETTER A WITH TILDE
    "\u00c4": "A",  # LATIN CAPITAL LETTER A WITH DIAERESIS
    "\u00c5": "A",  # LATIN CAPITAL LETTER A WITH RING ABOVE
    "\u00c6": "AE",  # LATIN CAPITAL LETTER AE
    "\u00c7": "C",  # LATIN CAPITAL LETTER C WITH CEDILLA
    "\u00c8": "E",  # LATIN CAPITAL LETTER E WITH GRAVE
    "\u00c9": "E",  # LATIN CAPITAL LETTER E WITH ACUTE
    "\u00ca": "E",  # LATIN CAPITAL LETTER E WITH CIRCUMFLEX
    "\u00cb": "E",  # LATIN CAPITAL LETTER E WITH DIAERESIS
    "\u00cc": "I",  # LATIN CAPITAL LETTER I WITH GRAVE
    "\u00cd": "I",  # LATIN CAPITAL LETTER I WITH ACUTE
    "\u00ce": "I",  # LATIN CAPITAL LETTER I WITH CIRCUMFLEX
    "\u00cf": "I",  # LATIN CAPITAL LETTER I WITH DIAERESIS
    "\u00d0": "D",  # LATIN CAPITAL LETTER ETH
    "\u00d1": "N",  # LATIN CAPITAL LETTER N WITH TILDE
    "\u00d2": "O",  # LATIN CAPITAL LETTER O WITH GRAVE
    "\u00d3": "O",  # LATIN CAPITAL LETTER O WITH ACUTE
    "\u00d4": "O",  # LATIN CAPITAL LETTER O WITH CIRCUMFLEX
    "\u00d5": "O",  # LATIN CAPITAL LETTER O WITH TILDE
    "\u00d6": "O",  # LATIN CAPITAL LETTER O WITH DIAERESIS
    "\u00d8": "O",  # LATIN CAPITAL LETTER O WITH STROKE
    "\u00d9": "U",  # LATIN CAPITAL LETTER U WITH GRAVE
    "\u00da": "U",  # LATIN CAPITAL LETTER U WITH ACUTE
    "\u00db": "U",  # LATIN CAPITAL LETTER U WITH CIRCUMFLEX
    "\u00dc": "U",  # LATIN CAPITAL LETTER U WITH DIAERESIS
    "\u00dd": "Y",  # LATIN CAPITAL LETTER Y WITH ACUTE
    "\u00de": "TH",  # LATIN CAPITAL LETTER THORN
    "\u00df": "ss",  # LATIN SMALL LETTER SHARP S
    "\u00e0": "a",  # LATIN SMALL LETTER A WITH GRAVE
    "\u00e1": "a",  # LATIN SMALL LETTER A WITH ACUTE
    "\u00e2": "a",  # LATIN SMALL LETTER A WITH CIRCUMFLEX
    "\u00e3": "a",  # LATIN SMALL LETTER A WITH TILDE
    "\u00e4": "a",  # LATIN SMALL LETTER A WITH DIAERESIS
    "\u00e5": "a",  # LATIN SMALL LETTER A WITH RING ABOVE
    "\u00e6": "ae",  # LATIN SMALL LETTER AE
    "\u00e7": "c",  # LATIN SMALL LETTER C WITH CEDILLA
    "\u00e8": "e",  # LATIN SMALL LETTER E WITH GRAVE
    "\u00e9": "e",  # LATIN SMALL LETTER E WITH ACUTE
    "\u00ea": "e",  # LATIN SMALL LETTER E WITH CIRCUMFLEX
    "\u00eb": "e",  # LATIN SMALL LETTER E WITH DIAERESIS
    "\u00ec": "i",  # LATIN SMALL LETTER I WITH GRAVE
    "\u00ed": "i",  # LATIN SMALL LETTER I WITH ACUTE
    "\u00ee": "i",  # LATIN SMALL LETTER I WITH CIRCUMFLEX
    "\u00ef": "i",  # LATIN SMALL LETTER I WITH DIAERESIS
    "\u00f0": "d",  # LATIN SMALL LETTER ETH
    "\u00f1": "n",  # LATIN SMALL LETTER N WITH TILDE
    "\u00f2": "o",  # LATIN SMALL LETTER O WITH GRAVE
    "\u00f3": "o",  # LATIN SMALL LETTER O WITH ACUTE
    "\u00f4": "o",  # LATIN SMALL LETTER O WITH CIRCUMFLEX
    "\u00f5": "o",  # LATIN SMALL LETTER O WITH TILDE
    "\u00f6": "o",  # LATIN SMALL LETTER O WITH DIAERESIS
    "\u00f8": "o",  # LATIN SMALL LETTER O WITH STROKE
    "\u00f9": "u",  # LATIN SMALL LETTER U WITH GRAVE
    "\u00fa": "u",  # LATIN SMALL LETTER U WITH ACUTE
    "\u00fb": "u",  # LATIN SMALL LETTER U WITH CIRCUMFLEX
    "\u00fc": "u",  # LATIN SMALL LETTER U WITH DIAERESIS
    "\u00fd": "y",  # LATIN SMALL LETTER Y WITH ACUTE
    "\u00fe": "th",  # LATIN SMALL LETTER THORN
    "\u00ff": "y",  # LATIN SMALL LETTER Y WITH DIAERESIS
}
