"""Tests for SVG support: sniffing, defusedxml validation, rasterisation hop.

The rasterisation path itself requires libcairo at runtime, which is
present on Home Assistant OS / Container but not on every dev box. The
``cairosvg`` module is therefore replaced via :data:`sys.modules` so the
pipeline can be exercised end-to-end without dlopen'ing libcairo; the
validation-only tests (sniff + defusedxml) need no system libraries.
"""

from __future__ import annotations

import base64
from collections.abc import Iterator
from contextlib import contextmanager
import io
import os
import sys
import types
from typing import Any

from homeassistant.exceptions import HomeAssistantError
from PIL import Image
import pytest

from custom_components.escpos_printer.printer.image_processor import (
    ImageProcessOptions,
    process_image_from_bytes,
)
from custom_components.escpos_printer.security import (
    MAX_PROCESSED_HEIGHT,
    MAX_SVG_ELEMENTS,
    MAX_SVG_SIZE_BYTES,
    MAX_SVG_USE_ELEMENTS,
    is_svg_bytes,
    validate_base64_image,
    validate_svg_bytes,
)

_MINIMAL_SVG = (
    b'<?xml version="1.0"?>\n'
    b'<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32">'
    b'<rect width="32" height="32" fill="black"/></svg>'
)


# ---------------------------------------------------------------------------
# is_svg_bytes — first-bytes sniffing
# ---------------------------------------------------------------------------


class TestIsSvgBytes:
    @pytest.mark.parametrize(
        "raw",
        [
            _MINIMAL_SVG,
            b'<svg xmlns="http://www.w3.org/2000/svg"/>',
            b"  \n<?xml version='1.0'?><svg/>",
            b"\xef\xbb\xbf<svg/>",  # UTF-8 BOM
            b"<!-- a comment first --><svg/>",
        ],
    )
    def test_recognises_svg(self, raw: bytes) -> None:
        assert is_svg_bytes(raw) is True

    @pytest.mark.parametrize(
        "raw",
        [
            b"\x89PNG\r\n\x1a\n",  # PNG magic
            b"\xff\xd8\xff",  # JPEG SOI
            b"GIF89a",
            b"",
            b"not xml at all",
        ],
    )
    def test_does_not_recognise_raster(self, raw: bytes) -> None:
        assert is_svg_bytes(raw) is False

    @pytest.mark.parametrize(
        "raw",
        [
            # XHTML / HTML5 — root is <html>, not <svg>
            b'<?xml version="1.0"?><!DOCTYPE html><html><body/></html>',
            b'<!DOCTYPE html><html lang="en"><body/></html>',
            # RSS, Atom, RDF — common non-SVG XML payloads
            b'<?xml version="1.0"?><rss version="2.0"><channel/></rss>',
            b'<feed xmlns="http://www.w3.org/2005/Atom"><id>x</id></feed>',
            b'<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"/>',
            # Comment + non-SVG root
            b"<!-- copyright header --><html/>",
            # DOCTYPE without entities, then non-SVG root
            b'<?xml version="1.0"?><!DOCTYPE rss><rss/>',
        ],
    )
    def test_does_not_recognise_non_svg_xml(self, raw: bytes) -> None:
        # Tightened sniff (F1 / F-MED-6): generic XML must route through
        # the raster path so the user sees a meaningful Pillow error
        # rather than a misleading "Invalid or unsafe SVG" wrapper.
        assert is_svg_bytes(raw) is False

    def test_recognises_svg_after_doctype(self) -> None:
        # Inkscape historically emits `<!DOCTYPE svg PUBLIC ...>` ahead
        # of the root element. The sniff must accept this shape.
        raw = (
            b'<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
            b'<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" '
            b'"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n'
            b'<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1"/>'
        )
        assert is_svg_bytes(raw) is True

    def test_recognises_svg_after_multiple_comments(self) -> None:
        # Some toolchains prepend multiple leading comments.
        raw = (
            b"<!-- copyright header -->"
            b"<!-- generated by tool -->"
            b'<svg xmlns="http://www.w3.org/2000/svg"/>'
        )
        assert is_svg_bytes(raw) is True

    def test_recognises_uppercase_svg_root(self) -> None:
        # Per XML 1.0, element names are case-sensitive; however SVG
        # exporters occasionally emit case-variant tags. The sniff is
        # case-insensitive because the downstream validate_svg_bytes
        # parses with defusedxml and confirms the actual root tag.
        assert is_svg_bytes(b"<SVG/>") is True

    def test_rejects_non_bytes(self) -> None:
        assert is_svg_bytes("not bytes") is False  # type: ignore[arg-type]


# ---------------------------------------------------------------------------
# validate_svg_bytes — defusedxml-backed XML safety gate
# ---------------------------------------------------------------------------


class TestValidateSvgBytes:
    def test_accepts_minimal_svg(self) -> None:
        assert validate_svg_bytes(_MINIMAL_SVG) == _MINIMAL_SVG

    def test_rejects_oversized_payload(self) -> None:
        # Pad past the cap with a benign attribute body so the size check
        # fires before the parser ever runs.
        padding = b"a" * (MAX_SVG_SIZE_BYTES + 1)
        with pytest.raises(HomeAssistantError, match="too large"):
            validate_svg_bytes(padding)

    def test_rejects_non_bytes(self) -> None:
        with pytest.raises(HomeAssistantError, match="bytes"):
            validate_svg_bytes("not bytes")  # type: ignore[arg-type]

    def test_rejects_malformed_xml(self) -> None:
        with pytest.raises(HomeAssistantError, match="Invalid or unsafe SVG"):
            validate_svg_bytes(b"<svg><not-closed>")

    def test_rejects_non_svg_root(self) -> None:
        with pytest.raises(HomeAssistantError, match="root element"):
            validate_svg_bytes(b"<html><body/></html>")

    def test_rejects_entity_expansion_billion_laughs(self) -> None:
        # Defusedxml refuses ENTITY declarations outright (EntitiesForbidden).
        # The exact wording comes from defusedxml; we just require that the
        # validator returns a HomeAssistantError rather than rendering it.
        bomb = (
            b'<?xml version="1.0"?>\n'
            b"<!DOCTYPE lolz [\n"
            b'  <!ENTITY lol "lol">\n'
            b'  <!ENTITY lol2 "&lol;&lol;&lol;&lol;&lol;">\n'
            b"]>\n"
            b'<svg xmlns="http://www.w3.org/2000/svg">&lol2;</svg>'
        )
        with pytest.raises(HomeAssistantError, match="Invalid or unsafe SVG"):
            validate_svg_bytes(bomb)

    def test_rejects_external_entity_reference(self) -> None:
        xxe = (
            b'<?xml version="1.0"?>\n'
            b'<!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>\n'
            b'<svg xmlns="http://www.w3.org/2000/svg">&xxe;</svg>'
        )
        with pytest.raises(HomeAssistantError, match="Invalid or unsafe SVG"):
            validate_svg_bytes(xxe)

    def test_accepts_boundary_element_count(self) -> None:
        # MAX_SVG_ELEMENTS counts every node including the root, so we
        # pack ``MAX - 1`` children to land exactly at the cap.
        children = b"".join(
            b'<rect width="1" height="1"/>' for _ in range(MAX_SVG_ELEMENTS - 1)
        )
        doc = b'<svg xmlns="http://www.w3.org/2000/svg">' + children + b"</svg>"
        # No exception — exactly at the cap is acceptable.
        validate_svg_bytes(doc)

    def test_rejects_over_element_count(self) -> None:
        # MAX_SVG_ELEMENTS + 1 child elements + the root tips us over.
        children = b"".join(
            b'<rect width="1" height="1"/>' for _ in range(MAX_SVG_ELEMENTS)
        )
        doc = b'<svg xmlns="http://www.w3.org/2000/svg">' + children + b"</svg>"
        with pytest.raises(HomeAssistantError, match="too many elements"):
            validate_svg_bytes(doc)

    def test_rejects_over_use_count(self) -> None:
        uses = b"".join(
            b'<use href="#a"/>' for _ in range(MAX_SVG_USE_ELEMENTS + 1)
        )
        doc = b'<svg xmlns="http://www.w3.org/2000/svg">' + uses + b"</svg>"
        with pytest.raises(HomeAssistantError, match="<use>"):
            validate_svg_bytes(doc)

    def test_rejects_over_use_count_xlink_href(self) -> None:
        # F-T-MED-5: Inkscape and SVG 1.1 use ``xlink:href`` instead of
        # ``href``. The tag name is still ``<use>``, so the cap fires
        # the same way; this test pins that contract.
        uses = b"".join(
            b'<use xlink:href="#a"/>' for _ in range(MAX_SVG_USE_ELEMENTS + 1)
        )
        doc = (
            b'<svg xmlns="http://www.w3.org/2000/svg" '
            b'xmlns:xlink="http://www.w3.org/1999/xlink">'
            + uses
            + b"</svg>"
        )
        with pytest.raises(HomeAssistantError, match="<use>"):
            validate_svg_bytes(doc)

    def test_rejects_deeply_nested_over_element_count(self) -> None:
        # F-T-MED-4: the element-count cap must hold regardless of
        # tree shape. Flat siblings are tested above; this exercises
        # the same iter() traversal against a 5000-deep nested tree.
        # Build by string concat so we never blow Python's recursion
        # limit while constructing the test fixture.
        depth = MAX_SVG_ELEMENTS + 1
        doc = (
            b'<svg xmlns="http://www.w3.org/2000/svg">'
            + b"<g>" * depth
            + b"</g>" * depth
            + b"</svg>"
        )
        with pytest.raises(HomeAssistantError, match="too many elements"):
            validate_svg_bytes(doc)

    def test_accepts_doctype_passthrough(self) -> None:
        # F-T-MED-1 + Phase-4 verification: defusedxml's
        # ``forbid_dtd=False`` default lets ``<!DOCTYPE svg PUBLIC ...>``
        # survive the parse. Tightening to ``forbid_dtd=True`` would
        # break legitimate Inkscape exports — pin the current contract
        # so a future "harden defusedxml" change cannot silently
        # regress real-world SVGs.
        inkscape_style = (
            b'<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
            b'<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" '
            b'"http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">\n'
            b'<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"/>'
        )
        # No exception — the DOCTYPE flavour Inkscape emits must pass.
        validate_svg_bytes(inkscape_style)


# ---------------------------------------------------------------------------
# data-URI flow: svg+xml now reaches validate_base64_image
# ---------------------------------------------------------------------------


class TestSvgDataUri:
    def test_base64_svg_data_uri_decodes(self) -> None:
        uri = "data:image/svg+xml;base64," + base64.b64encode(_MINIMAL_SVG).decode()
        assert validate_base64_image(uri) == _MINIMAL_SVG


# ---------------------------------------------------------------------------
# End-to-end image_processor hop — cairosvg patched so libcairo is optional
# ---------------------------------------------------------------------------


def _fake_png_bytes(width: int = 32, height: int = 32) -> bytes:
    """Return PNG bytes for a solid-grey image at the requested size."""
    img = Image.new("L", (width, height), color=128)
    bio = io.BytesIO()
    img.save(bio, format="PNG")
    return bio.getvalue()


@contextmanager
def _stub_cairosvg(svg2png_impl: Any) -> Iterator[types.ModuleType]:
    """Replace ``cairosvg`` in :data:`sys.modules` with a stub.

    The real ``cairosvg`` dlopen's libcairo on import, which is absent on
    most macOS dev machines and on slim CI containers. Replacing the
    module before ``svg_renderer`` resolves its lazy import lets us
    exercise the full pipeline without the system library.
    """
    stub = types.ModuleType("cairosvg")
    stub.svg2png = svg2png_impl  # type: ignore[attr-defined]
    original = sys.modules.get("cairosvg")
    sys.modules["cairosvg"] = stub
    try:
        yield stub
    finally:
        if original is None:
            sys.modules.pop("cairosvg", None)
        else:
            sys.modules["cairosvg"] = original


class TestProcessImageFromBytesSvgHop:
    def test_svg_bytes_get_rasterised_then_decoded(self) -> None:
        captured: dict[str, object] = {}

        def fake_svg2png(**kwargs: Any) -> None:
            captured.update(kwargs)
            png = _fake_png_bytes(64, 32)
            kwargs["write_to"].write(png)

        with _stub_cairosvg(fake_svg2png):
            opts = ImageProcessOptions(width=384, profile_width=384)
            img = process_image_from_bytes(_MINIMAL_SVG, opts)

        assert captured["output_width"] == 384
        # output_height is pinned to MAX_PROCESSED_HEIGHT so a hostile
        # SVG declaring a huge declared height cannot trick cairo into
        # allocating an unbounded raster surface.
        assert captured["output_height"] == MAX_PROCESSED_HEIGHT
        # unsafe=False is what stops external-resource fetches in
        # cairosvg 2.9 (the parser auto-installs safe_fetch). Our code
        # must not be passing url_fetcher — that kwarg is not accepted
        # by cairosvg.svg2png().
        assert captured["unsafe"] is False
        assert "url_fetcher" not in captured
        assert img.mode == "1"

    def test_svg_validation_runs_before_cairosvg(self) -> None:
        calls: list[dict[str, Any]] = []

        def fake_svg2png(**kwargs: Any) -> None:
            calls.append(kwargs)

        with _stub_cairosvg(fake_svg2png):
            xxe = (
                b'<?xml version="1.0"?>\n'
                b'<!DOCTYPE foo [<!ENTITY xxe SYSTEM "file:///etc/passwd">]>\n'
                b'<svg xmlns="http://www.w3.org/2000/svg">&xxe;</svg>'
            )
            with pytest.raises(HomeAssistantError, match="Invalid or unsafe SVG"):
                process_image_from_bytes(xxe, ImageProcessOptions(width=384))
        assert calls == []

    def test_raster_image_path_unaffected(self) -> None:
        calls: list[dict[str, Any]] = []

        def fake_svg2png(**kwargs: Any) -> None:
            calls.append(kwargs)

        # PNG input must flow through the existing Pillow path without
        # invoking the cairosvg stub at all.
        with _stub_cairosvg(fake_svg2png):
            png = _fake_png_bytes(100, 50)
            opts = ImageProcessOptions(width=200)
            img = process_image_from_bytes(png, opts)
        assert img.mode == "1"
        assert calls == []

    def test_aspect_ratio_bomb_yields_bounded_surface(self) -> None:
        # F-T-MED-3 regression — the exact decompression-bomb payload
        # from the Phase-2 security report. The fix (F-HIGH-1) pinned
        # ``output_height=MAX_PROCESSED_HEIGHT`` in svg_renderer, so
        # cairosvg now allocates a bounded surface regardless of the
        # SVG's declared dimensions. This test asserts the kwargs we
        # send to cairosvg are still the bounded pair — the next
        # refactor that drops ``output_height`` would re-introduce
        # the OOM vector and trip this assertion.
        bomb = (
            b'<svg xmlns="http://www.w3.org/2000/svg" '
            b'width="1" height="999999">'
            b'<rect width="1" height="999999"/></svg>'
        )
        captured: dict[str, Any] = {}

        def fake_svg2png(**kwargs: Any) -> None:
            captured.update(kwargs)
            kwargs["write_to"].write(_fake_png_bytes(384, 384))

        with _stub_cairosvg(fake_svg2png):
            process_image_from_bytes(bomb, ImageProcessOptions(width=384))

        assert captured["output_width"] == 384
        assert captured["output_height"] == MAX_PROCESSED_HEIGHT
        assert captured["unsafe"] is False

    def test_memory_error_from_cairo_is_not_wrapped(self) -> None:
        # F-T-HIGH-2 regression — ``rasterise_svg_to_png`` deliberately
        # re-raises MemoryError / SystemError unchanged so the HA
        # process supervisor can react. A refactor that collapses to a
        # single ``except Exception`` would silently regress this.
        def fake_svg2png(**kwargs: Any) -> None:
            raise MemoryError("simulated cairo allocation failure")

        with _stub_cairosvg(fake_svg2png):
            with pytest.raises(MemoryError, match="simulated cairo"):
                process_image_from_bytes(
                    _MINIMAL_SVG, ImageProcessOptions(width=384)
                )

    def test_kill_switch_env_refuses_svg_before_render(
        self,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        # F-CI-MED-1: ``ESCPOS_DISABLE_SVG`` is the emergency
        # kill-switch for a hypothetical cairosvg / libcairo CVE.
        # The renderer must refuse before invoking cairosvg, so a
        # stub that records calls must NOT be called.
        calls: list[dict[str, Any]] = []

        def fake_svg2png(**kwargs: Any) -> None:
            calls.append(kwargs)

        monkeypatch.setenv("ESCPOS_DISABLE_SVG", "1")
        with _stub_cairosvg(fake_svg2png):
            with pytest.raises(HomeAssistantError, match="SVG rendering is disabled"):
                process_image_from_bytes(
                    _MINIMAL_SVG, ImageProcessOptions(width=384)
                )
        assert calls == [], "cairosvg must not be called when kill-switch is set"

    @pytest.mark.parametrize("value", ["0", "false", "no", "off", ""])
    def test_kill_switch_env_falsy_does_not_refuse(
        self,
        monkeypatch: pytest.MonkeyPatch,
        value: str,
    ) -> None:
        # The truthy-set is intentionally narrow so a stray
        # ``ESCPOS_DISABLE_SVG=`` doesn't break SVG support for users
        # who don't realise the var is set in their shell env.
        monkeypatch.setenv("ESCPOS_DISABLE_SVG", value)

        def fake_svg2png(**kwargs: Any) -> None:
            kwargs["write_to"].write(_fake_png_bytes(32, 32))

        with _stub_cairosvg(fake_svg2png):
            process_image_from_bytes(
                _MINIMAL_SVG, ImageProcessOptions(width=384)
            )


# ---------------------------------------------------------------------------
# Real-cairosvg integration test — guards against the kwarg-mismatch
# class of regression that the sys.modules stub silently swallows.
# Skipped automatically when libcairo (or cairosvg itself) is absent.
# ---------------------------------------------------------------------------


class TestRealCairosvgBinding:
    def test_real_cairosvg_renders_minimal_svg(self) -> None:
        """Exercise the actual cairosvg.svg2png kwarg surface.

        Regression guard for the kwarg-mismatch class of bug: the
        stub-based tests above accept ``**kwargs`` unconditionally, so
        ``cairosvg.svg2png(foo_bar=True)`` would silently pass against
        them. This test imports the real cairosvg (skipping if
        libcairo is unavailable on the host) and confirms our exact
        call signature is accepted end-to-end.
        """
        try:
            import cairosvg
        except (ImportError, OSError) as exc:
            # F-CI-CRIT-1 + F-T-HIGH-1: this test is the regression
            # guard for the cairosvg-API-mismatch class of bug found
            # during review. It MUST run in CI; locally it can skip on
            # dev boxes without libcairo. The CI=true env var is set in
            # validate.yml so a missing libcairo there is a hard error,
            # not a silent skip.
            if os.environ.get("CI") == "true":
                raise RuntimeError(
                    "CI must have libcairo installed so TestRealCairosvgBinding "
                    "runs — see validate.yml. Skip refused."
                ) from exc
            pytest.skip(f"cairosvg / libcairo not available: {exc}")

        from custom_components.escpos_printer.printer.svg_renderer import (
            rasterise_svg_to_png,
        )

        png = rasterise_svg_to_png(_MINIMAL_SVG, output_width=64)
        # PNG magic number — proves cairosvg produced a real raster.
        assert png.startswith(b"\x89PNG\r\n\x1a\n")
        # Silence unused-import warning while keeping the explicit
        # import as documentation of the dependency under test.
        assert cairosvg is not None


# ---------------------------------------------------------------------------
# F-T-HIGH-3 — service-chain integration: walk the full
# resolve_image_bytes → process_image_from_bytes pipeline for each
# SVG source kind (data URI, local file, HTTP). cairosvg is stubbed
# via sys.modules so libcairo is not required to run the suite.
# ---------------------------------------------------------------------------


async def _resolve_then_render(hass: Any, source: str) -> dict[str, Any]:
    """Walk resolve_image_bytes → process_image_from_bytes; return cairosvg kwargs."""
    from custom_components.escpos_printer.image_sources import (
        resolve_image_bytes,
    )

    captured: dict[str, Any] = {}

    def fake_svg2png(**kwargs: Any) -> None:
        captured.update(kwargs)
        kwargs["write_to"].write(_fake_png_bytes(64, 32))

    raw, _hint = await resolve_image_bytes(hass, source)
    with _stub_cairosvg(fake_svg2png):
        process_image_from_bytes(raw, ImageProcessOptions(width=384))
    return captured


class TestSvgServiceChain:
    async def test_data_uri_svg_walks_full_pipeline(self, hass: Any) -> None:
        uri = "data:image/svg+xml;base64," + base64.b64encode(_MINIMAL_SVG).decode()
        captured = await _resolve_then_render(hass, uri)
        assert captured["output_width"] == 384
        assert captured["output_height"] == MAX_PROCESSED_HEIGHT
        assert captured["unsafe"] is False

    async def test_local_svg_file_walks_full_pipeline(
        self,
        hass: Any,
        tmp_path: Any,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        path = tmp_path / "logo.svg"
        path.write_bytes(_MINIMAL_SVG)
        monkeypatch.setattr(hass.config, "is_allowed_path", lambda _p: True)
        captured = await _resolve_then_render(hass, str(path))
        assert captured["output_width"] == 384

    async def test_local_svg_rejected_at_fetch_when_above_svg_cap(
        self,
        hass: Any,
        tmp_path: Any,
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        # F-MED-1: when the file extension is .svg, the per-read cap
        # tightens to MAX_SVG_SIZE_BYTES (1 MB) rather than the 10 MB
        # raster cap. A file larger than 1 MB must be refused at the
        # fetcher boundary (via the stat-size check in
        # ``open_local_image_no_follow``), never reaching
        # ``validate_svg_bytes``. The downstream validator's own
        # size cap is exercised separately by
        # ``TestValidateSvgBytes.test_rejects_oversized_payload``.
        from custom_components.escpos_printer.image_sources import (
            resolve_image_bytes,
        )
        from custom_components.escpos_printer.security import MAX_SVG_SIZE_BYTES

        path = tmp_path / "big.svg"
        # Write just-over the SVG cap with bytes that are NOT inside a
        # valid <svg> root, so if the fetcher ever stopped enforcing
        # the SVG cap and delegated to the validator, the validator
        # would fail with a different message (XML parse error) — which
        # would make this test fail loudly rather than silently shift
        # to exercising the wrong gate.
        path.write_bytes(b"x" * (MAX_SVG_SIZE_BYTES + 1))
        monkeypatch.setattr(hass.config, "is_allowed_path", lambda _p: True)
        with pytest.raises(HomeAssistantError, match="too large"):
            await resolve_image_bytes(hass, str(path))
